apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment2
  labels:
    app: mongo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo2
  template:
    metadata:
      labels:
        app: mongo2
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret2
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret2
              key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service2
spec:
  selector:
    app: mongo2
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27019
